# Copyright 2025 Shuai Zhang
# SPDX-License-Identifier: LGPL-3.0-or-later WITH LGPL-3.0-linking-exception

[tools]
go = "latest"
"go:github.com/B1NARY-GR0UP/nwa" = "latest"
hk = "latest"
node = "lts"
"npm:markdownlint-cli2" = "latest"
"npm:prettier" = "latest"
pkl = "latest"
